# Site settings
title: Rebecca Gilmore
email: rebeccacgilmore@gmail.com
url: https://rcgilmore.github.io/
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Web Developer - Dancer - World Traveler"
meta_author: Gilmore Rebecca
repository: rcgilmore/rcgilmore.github.io

# Google webmaster tools
google_verify:
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-82472992-1', 'auto');
  ga('send', 'pageview');

</script>
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 49404F #80B3FF
  primary-rgb: "73,64,79" #"128,179,255"
  secondary: 596166 #FD6E8A
  secondary-dark: 644D52 #A2122F

# Footer settings
footer:
  copyright: Rebecca Gilmore
  # location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/rebeccacgilmore
  - title: facebook
    url: http://facebook.com/LilBegi
  - title: instagram
    url: https://www.instagram.com/lil_begi/
  - title: github
    url: http://github.com/rcgilmore

# Postal address (add as many lines as necessary)
# address:
#   - line: 2901 Philadelphia Cove
#   - line: Jonesboro, AR 72401

# Credits content
# credits:

# Build settings
markdown: kramdown
permalink: pretty
